
CREATE DATABASE Biblioteca;
GO

USE Biblioteca;
GO


CREATE TABLE LECTOR (
    NumLector INT NOT NULL,
    NumMembrecia NVARCHAR(30) NOT NULL,
    Nombre NVARCHAR(10) NOT NULL,
    ApellidoPaterno NVARCHAR(10) NOT NULL,
    ApellidoMaterno NVARCHAR(10) NOT NULL,
    CONSTRAINT PK_LECTOR PRIMARY KEY (NumLector)
);
GO


CREATE TABLE LIBRO (
    Autor NVARCHAR(20) NOT NULL,
    Titulo NVARCHAR(30) NOT NULL,
    CantidadLibro VARCHAR(10) NOT NULL,
    NumeroISRM VARCHAR(20) NOT NULL, 
    NumLibro INT NOT NULL,
    CONSTRAINT PK_LIBRO PRIMARY KEY (NumLibro)
);
GO


CREATE TABLE PRESTA (
    IdPresta INT NOT NULL,
    NumLibro INT NOT NULL,
    NumLector INT NOT NULL,
    Titulo NVARCHAR(30) NOT NULL,
    Autor NVARCHAR(20) NOT NULL,
    NombreLector NVARCHAR(20) NOT NULL,
    CONSTRAINT PK_PRESTA PRIMARY KEY (IdPresta),
    CONSTRAINT FK_PRESTA_LIBRO FOREIGN KEY (NumLibro) 
        REFERENCES LIBRO(NumLibro),
    CONSTRAINT FK_PRESTA_LECTOR FOREIGN KEY (NumLector) 
        REFERENCES LECTOR(NumLector)
);
GO