CREATE DATABASE CompanyDB;
GO

USE CompanyDB;
GO

CREATE TABLE DEPARTMENT (
    DepartmentId INT NOT NULL,
    NomDepto NVARCHAR(10),
    NameDepto NVARCHAR(50),
    Manager INT,
    StartDate DATE,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DepartmentId)
);
GO

CREATE TABLE EMPLOYEE (
    EmployId INT NOT NULL,
    SSN NVARCHAR(11),
    Firstname NVARCHAR(50),
    Lastname NVARCHAR(50),
    Namee NVARCHAR(100),
    Salary DECIMAL(10,2),
    Birthday DATE,
    Addresss NVARCHAR(100),
    Sex CHAR(1),
    Department INT,
    Jefe INT,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EmployId),
    CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (Department) REFERENCES DEPARTMENT(DepartmentId),
    CONSTRAINT FK_EMPLOYEE_JEFE FOREIGN KEY (Jefe) REFERENCES EMPLOYEE(EmployId)
);
GO

ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_MANAGER FOREIGN KEY (Manager) REFERENCES EMPLOYEE(EmployId);
GO

CREATE TABLE PROYECT (
    ProyectId INT NOT NULL,
    NomProyect NVARCHAR(10),
    NameProyect NVARCHAR(100),
    Locationn NVARCHAR(100),
    DepartmentId INT,
    CONSTRAINT PK_PROYECT PRIMARY KEY (ProyectId),
    CONSTRAINT FK_PROYECT_DEPARTMENT FOREIGN KEY (DepartmentId) REFERENCES DEPARTMENT(DepartmentId)
);
GO

CREATE TABLE WORKS_ON (
    EmployedId INT NOT NULL,
    ProyectId INT NOT NULL,
    Hourss DECIMAL(5,2),
    CONSTRAINT PK_WORKS_ON PRIMARY KEY (EmployedId, ProyectId),
    CONSTRAINT FK_WORKS_ON_EMPLOYEE FOREIGN KEY (EmployedId) REFERENCES EMPLOYEE(EmployId),
    CONSTRAINT FK_WORKS_ON_PROYECT FOREIGN KEY (ProyectId) REFERENCES PROYECT(ProyectId)
);
GO


CREATE TABLE DEPENDENT (
    Namee NVARCHAR(100) NOT NULL,
    Employeeid INT NOT NULL,
    Sex CHAR(1),
    Birthday DATE,
    Relationship NVARCHAR(50),
    CONSTRAINT PK_DEPENDENT PRIMARY KEY (Namee, Employeeid),
    CONSTRAINT FK_DEPENDENT_EMPLOYEE FOREIGN KEY (Employeeid) REFERENCES EMPLOYEE(EmployId)
);
GO